#!/bin/sh
id=${1:?gene, transcript or protein id}
expand=${2:-0}
url="http://rest.ensembl.org/lookup/id/$id?expand=$expand;content-type=application/json"
out=$(curl -sS -w "\n" $url)
echo $out | jq -S

# Print transcript info if querying a protein
if [[ "$id" == "ENSP*" ]]; then ensembl $(jq -r '.Parent' $out); fi
